import logging
from datetime import timedelta

from odoo import api, fields, models
from odoo.exceptions import UserError
from odoo.osv import expression

from ..models.documents_document import STATUS

_logger = logging.getLogger(__name__)


class MxEdiToRecordWizard(models.TransientModel):
    _name = "documents.mx_edi_to_record_wizard"
    _description = "MX EDI to Record"

    company_id = fields.Many2one(
        comodel_name="res.company",
        default=lambda self: self.env.company,
    )
    journal_id = fields.Many2one(
        comodel_name="account.journal",
        string="Journal",
        domain="[('type', '=', 'purchase'), ('company_id', '=', company_id)]",
        help="This journal will be used in the vendor bills generated by this document.",
    )
    line_ids = fields.One2many("documents.mx_edi_to_record_line", "wizard_id")
    count_lines = fields.Integer(compute="_compute_count_lines")

    @api.depends("line_ids")
    def _compute_count_lines(self):
        for wizard in self:
            wizard.count_lines = len(wizard.line_ids)

    def _prepare_line_vals(self, document):
        """Centralizes logic for preparing line values"""
        mx_edi_document = self.env["l10n_mx_edi.document"]
        account_move = self.env["account.move"]

        line_vals = {"document_id": document.id, "action": "create", "move_id": False}

        if not document.datas or document.l10n_mx_edi_is_cfdi_payment:
            line_vals["action"] = "none"
            return line_vals

        try:
            cfdi_infos = mx_edi_document._decode_cfdi_attachment(document.raw)
            uuid = cfdi_infos.get("uuid")

            if document.vendor_bill_name:
                line_vals["action"] = "none"
            elif uuid:
                existing_move = account_move.search(
                    [
                        ("l10n_mx_edi_cfdi_uuid", "=", uuid),
                        ("company_id", "=", self.env.company.id),
                    ],
                    limit=1,
                )
                if existing_move:
                    line_vals.update({"action": "assign", "move_id": existing_move.id})
        except Exception as e:
            _logger.error("Error processing document %s: %s", document.name, str(e))

        return line_vals

    @api.onchange("journal_id")
    def _onchange_journal_id(self):
        """Clear move_id when journal changes to avoid inconsistencies"""
        if not self.line_ids:
            return

        # Preserve existing documents but recompute all other values
        document_ids = self.line_ids.mapped("document_id")
        self.line_ids = [(5, 0, 0)] + [(0, 0, self._prepare_line_vals(doc)) for doc in document_ids]

    @api.model
    def default_get(self, fields_list):
        """Initialize wizard with lines from selected documents."""
        res = super().default_get(fields_list)
        document_ids = self.env["documents.document"]
        if self._context.get("active_ids") and self._context.get("active_model") == "documents.document":
            document_ids = self.env["documents.document"].browse(self._context.get("active_ids", []))
        elif self._context.get("default_document_ids"):
            document_ids = self.env["documents.document"].browse(self._context.get("default_document_ids", []))

        if document_ids:
            res["line_ids"] = [(0, 0, self._prepare_line_vals(doc)) for doc in document_ids]

        return res

    def create_records(self):
        """Create or link account moves from the selected documents.

        This method handles two main scenarios:
        1. Creating new bills from CFDI documents when action='create'
        2. Linking existing bills when action='assign'

        Returns:
            dict: Window action to display the created/linked moves
            or closes the window if no moves were processed.

        Raises:
            UserError: If any error occurs during processing
        """
        move_ids = []
        account_move = self.env["account.move"]
        mx_edi_document = self.env["l10n_mx_edi.document"]
        # Process only lines that require action (filter out 'none' actions)
        for line in self.line_ids.filtered(lambda ln: ln.action != "none"):
            document = line.document_id
            move = line.move_id

            if document.l10n_mx_edi_is_cfdi_payment:
                raise UserError(
                    self.env._(
                        "Only Vendor Bill Documents are allowed to create or assign, '%s' is a payment complement",
                        document.name,
                    )
                )

            # Create new move if required
            if line.action == "create":
                try:
                    # Step 1: Extract and validate CFDI data
                    cfdi_infos = mx_edi_document._decode_cfdi_attachment(document.raw)
                    uuid = cfdi_infos.get("uuid", "").upper()
                    if not uuid:
                        raise UserError(self.env._("Could not extract UUID from document %s", document.name))

                    # Step 2: Prepare invoice values from CFDI
                    vals = mx_edi_document._prepare_invoice_vals(cfdi_infos, self.journal_id)
                    vals.update({"l10n_mx_edi_cfdi_uuid": uuid})

                    # Step 3: Create the account move
                    move = account_move.create(vals)
                except Exception as e:
                    raise UserError(
                        self.env._("Error creating invoice from document {}: {}").format(document.name, str(e))
                    )

            # Update document and move relationship
            try:
                attachment = document.attachment_id

                # Link the attachment to the account move
                attachment.with_context(no_document=True).write(
                    {
                        "res_model": "account.move",
                        "res_id": move.id,
                    }
                )

                # Ensure CFDI attachment is set on the move if missing
                if not move.l10n_mx_edi_cfdi_uuid:
                    cfdi_infos = mx_edi_document._decode_cfdi_attachment(document.raw)
                    move.l10n_mx_edi_cfdi_uuid = cfdi_infos.get("uuid", "").upper()

                move_ids.append(move.id)

                # Create MX Document for Vendor Bills
                file_data_list = attachment._unwrap_edi_attachments()
                for file_data in file_data_list:
                    # Import CFDI if it's a valid CFDI file and no documents exist yet
                    if file_data.get("is_cfdi", False) and not move.l10n_mx_edi_invoice_document_ids:
                        account_move._l10n_mx_edi_import_cfdi_invoice(move, file_data)

                move.l10n_mx_edi_cfdi_try_sat()

                # If cancelled CFDI cancel account move
                if move.l10n_mx_edi_cfdi_sat_state == "cancelled":
                    move.action_post()
                    move.button_cancel()

            except Exception as e:
                raise UserError(self.env._("Error assigning invoice to document {}: {}").format(document.name, str(e)))

        # Return appropriate action based on results
        if not move_ids:
            return {"type": "ir.actions.act_window_close"}

        action = {
            "type": "ir.actions.act_window",
            "res_model": "account.move",
            "name": self.env._("Vendor Bills"),
            "view_mode": "list,form",
            "domain": [("id", "in", move_ids)],
            "context": dict(self._context),
        }

        # For single move, show form view directly
        if len(move_ids) == 1:
            record = account_move.browse(move_ids[0])
            action.update(
                {
                    "view_mode": "form",
                    "views": [(record.get_formview_id(), "form")],
                    "res_id": move_ids[0],
                }
            )

        return action


class MxEdiToRecordLine(models.TransientModel):
    _name = "documents.mx_edi_to_record_line"

    wizard_id = fields.Many2one("documents.mx_edi_to_record_wizard", required=True, ondelete="cascade")
    document_id = fields.Many2one("documents.document", required=True, readonly=True)
    partner_id = fields.Many2one(related="document_id.partner_id", readonly=True)
    journal_id = fields.Many2one(related="wizard_id.journal_id", readonly=True)
    allowed_move_ids = fields.Many2many("account.move", compute="_compute_allowed_move_ids")
    action = fields.Selection(
        selection=[
            ("create", "Create"),
            ("assign", "Assign"),
            ("none", "Nothing to do"),
        ],
        default="create",
        required=True,
    )
    move_id = fields.Many2one(
        "account.move",
        string="Vendor Bill",
        domain="[('id', 'in', allowed_move_ids)]",
        help="Select an existing vendor bill that matches this document or leave empty to create a new one",
    )

    @api.depends("action")
    def _compute_allowed_move_ids(self):
        """Compute possible vendor bills/credit notes for assignment."""
        mx_edi_document = self.env["l10n_mx_edi.document"]
        account_move = self.env["account.move"]
        for line in self:
            if line.action != "assign" or not line.document_id or not line.document_id.datas or not line.journal_id:
                line.allowed_move_ids = False
                continue

            allowed_moves = account_move
            try:
                cfdi_infos = mx_edi_document._decode_cfdi_attachment(line.document_id.raw)
                existing_move = account_move.search(
                    [
                        ("l10n_mx_edi_cfdi_uuid", "=", cfdi_infos.get("uuid")),
                        ("company_id", "=", self.env.company.id),
                    ],
                    limit=1,
                )
                if existing_move:
                    allowed_moves = existing_move
                else:
                    supplier_rfc = cfdi_infos.get("supplier_rfc")
                    amount_total = float(cfdi_infos.get("amount_total", 0.0) or 0.0)
                    emission_date_str = cfdi_infos.get("emission_date_str", "")

                    # Base domain for all searches
                    base_domain = [
                        ("state", "=", "draft"),
                        ("journal_id", "=", line.journal_id.id),
                        ("l10n_mx_edi_cfdi_uuid", "=", False),
                        "|",
                        ("move_type", "=", "in_invoice"),
                        ("move_type", "=", "in_refund"),
                    ]

                    # Strict matching
                    strict_domain = base_domain + [("amount_total", "=", amount_total)]
                    if supplier_rfc and line.partner_id:
                        strict_domain.append(("partner_id.vat", "=", supplier_rfc))

                    if emission_date_str:
                        try:
                            emission_date = fields.Date.from_string(emission_date_str.split()[0])
                            date_domain = [
                                "|",
                                "|",
                                ("invoice_date", "=", emission_date),
                                (
                                    "invoice_date",
                                    "=",
                                    emission_date + timedelta(days=1),
                                ),
                                (
                                    "invoice_date",
                                    "=",
                                    emission_date - timedelta(days=1),
                                ),
                            ]
                            strict_domain = expression.AND([strict_domain, date_domain])
                        except Exception:
                            _logger.info("CFDI date parsing failed: %s", emission_date_str)

                    allowed_moves = account_move.search(strict_domain, limit=10)

                    # Flexible matching if strict fails
                    if not allowed_moves and amount_total:
                        tolerance = amount_total * 0.001
                        flexible_domain = base_domain + [
                            ("amount_total", ">=", amount_total - tolerance),
                            ("amount_total", "<=", amount_total + tolerance),
                        ]
                        if supplier_rfc and line.partner_id:
                            flexible_domain.append(("partner_id.vat", "=", supplier_rfc))
                        allowed_moves = account_move.search(flexible_domain, limit=10)
            except Exception as e:
                _logger.error("Allowed moves computation failed: %s", str(e))

            line.allowed_move_ids = allowed_moves
