from . import account_account
from . import account_analytic_account
from . import account_analytic_line
from . import account_analytic_distribution_model
from . import account_asset
from . import account_bank_statement_line
from . import account_journal
from . import account_move
from . import account_move_line
from . import account_payment
from . import account_reconcile_model
from . import documents_document
from . import documents_tag
from . import fleet_vehicle
from . import fleet_vehicle_log
from . import gps_tracking_device
from . import hr_contract
from . import hr_payslip
from . import hr_payslip_run
from . import mrp_bom
from . import approval_category
from . import approval_request
from . import approval_product_line
from . import mrp_production
from . import pos_config
from . import pos_order
from . import pos_order_line
from . import pos_session
from . import product_category
from . import product_template
from . import purchase_bill_union
from . import purchase_order
from . import purchase_order_line
from . import project_task_lost_reason
from . import project_task
from . import res_company
from . import res_partner_age_range
from . import res_partner
from . import res_users
from . import sale_order
from . import sale_order_line
from . import stock_location
from . import stock_lot
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_picking_type
from . import stock_quant
from . import stock_scrap
from . import stock_picking_tracker
from . import bbva_parser
from . import res_config_settings
from . import l10n_mx_edi_document
from . import project_project
