from . import authorize_debt
from . import documents_link_to_record_wizard
from . import invoice_cash_discount
from . import invoice_line_price_history
from . import pos_cash_transfer_wizard
from . import purchase_order_line_price_history
from . import sale_order_line_price_history
from . import stock_quant_lot_update
from . import product_asset_log_import
from . import sale_target_wizard
from . import res_config_settings
