from . import test_account_analytic_line
from . import test_account_journal
from . import test_account_move
from . import test_account_payment_term
from . import test_hr_contract
from . import test_partner_age_range
from . import test_payroll
from . import test_pos_cash_transfer_wizard
from . import test_pos_stock
from . import test_purchase
from . import test_res_company
from . import test_sale
from . import test_stock_move_line
from . import test_users
