{
    "name": "Geospatial support for Odoo",
    "category": "GeoBI",
    "author": "Camptocamp,ACSONE SA/NV,Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "website": "https://github.com/OCA/geospatial",
    "depends": ["base", "web"],
    "data": [
        "security/data.xml",
        "security/ir.model.access.csv",
        "views/ir_model_view.xml",
        "views/ir_view_view.xml",
        "views/geo_raster_layer_view.xml",
        "views/geo_vector_layer_view.xml",
        "wizard/res_config_settings_views.xml",
        "wizard/geo_setup_wizard_views.xml",
        "wizard/geo_performance_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "base_geoengine/static/src/js/**/*",
            "base_geoengine/static/src/css/style.css",
            "web/static/src/libs/fontawesome/css/font-awesome.css",
            ("include", "web._assets_helpers"),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            ("include", "web._assets_bootstrap"),
        ],
        "base_geoengine.assets_jsLibs_geoengine": [
            "/base_geoengine/static/lib/ol-10.5.0/ol.js",
            "/base_geoengine/static/lib/chromajs-3.1.2/chroma.js",
            "/base_geoengine/static/lib/geostats-2.1.0/geostats.js",
            "/base_geoengine/static/lib/geostats-2.1.0/geostats.css",
        ],
    },
    "external_dependencies": {"python": ["shapely", "geojson", "simplejson"]},
    "installable": True,
    "pre_init_hook": "init_postgis",
}
