{
    "name": "Marin",
    "summary": """
    Instance creator for Marin. This is the app.
    """,
    "author": "Agro Marin",
    "website": "https://www.agromarin.mx",
    "license": "OPL-1",
    "category": "Installer",
    "version": "1.0",
    "depends": [
        "date_range",
        "board",
        "web_studio",
        "data_recycle",
        "knowledge",
        "calendar",
        "documents",
        "documents_expiry",
        "loyalty",
        "product_manufacturer",
        "crm",
        "survey",
        "appointment",
        "hr",
        "hr_skills",
        "hr_recruitment_survey",
        "hr_appraisal",
        "project",
        "project_forecast",
        "room",
        "fleet",
        "stock",
        "stock_barcode_quality_control",
        "mrp_product_expiry",
        # "stock_barcode_picking_batch",
        # "stock_3dpicking",
        "stock_barcode_mrp_subcontracting",
        "mrp_plm",
        "account",
        "account_debit_note",
        "product_margin",
        "account_move_name_sequence",
        # "account_move_operation",
        "account_reports_cash_basis",
        "account_consolidation",
        "documents_account",
        "documents_l10n_mx_edi",
        "l10n_mx_edi_extended",
        "l10n_mx_avoid_reversal_entry",
        "l10n_mx_partner_blocklist",
        # "l10n_mx_edi_refund",
        # "l10n_mx_edi_related_documents",
        "hr_payroll",
        "documents_hr_payroll",
        "hr_payroll_expense",
        "hr_expense_extract",
        "l10n_mx_edi_payslip",
        "purchase",
        "account_budget",
        "purchase_requisition_stock",
        "account_3way_match",
        "mrp_subcontracting_landed_costs",
        "purchase_team",
        "sale",
        "sale_management",
        "account_invoice_margin_sale",
        "sale_purchase_inter_company_rules",
        "delivery",
        "mrp_subcontracting_dropshipping",
        # "stock_move_location",
        "sale_commercial_partner",
        "sale_order_global_stock_route",
        "sale_renting",
        "point_of_sale",
        "pos_sale_margin",
        "pos_hr",
        "website",
        "website_sale_stock",
        "website_sale_picking",
        "website_event_sale",
        "website_crm_partner_assign",
        "website_slides",
        # "website_tiledesk",
        # "users_working_hours",
        # "syngenta_edi",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "data/ir_config_parameter_data.xml",
        "data/ir_actions_server_data.xml",
        "data/ir_cron_data.xml",
        "data/res_lang_data.xml",
        "data/ir_default_data.xml",
        "data/decimal_precision_data.xml",
        "data/mail_activity_data.xml",
        "data/res_config_settings_data.xml",
        "data/res_partner_age_range_data.xml",
        "data/res_bank_data.xml",
        "data/documents_folder_data.xml",
        "data/documents_facet_data.xml",
        "data/documents_tag_data.xml",
        "data/documents_partner_data.xml",
        "data/product_removal_data.xml",
        # "report/report_deliveryslip.xml",
        # "report/report_stock_picking_operations.xml",
        "report/report_invoice.xml",
        "report/report_payment.xml",
        "views/account_account_views.xml",
        "views/account_analytic_distribution_model_views.xml",
        "views/account_analytic_line_views.xml",
        "views/account_bank_statement_views.xml",
        "views/account_journal_views.xml",
        "views/account_move_views.xml",
        "views/account_move_line_views.xml",
        "views/account_payment_term_views.xml",
        "views/account_payment_views.xml",
        "views/crm_lead_views.xml",
        "views/documents_document_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/hr_expense_views.xml",
        # "views/hr_contract_views.xml",
        "views/hr_payslip_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/pos_session_views.xml",
        "views/product_category_views.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/purchase_order_views.xml",
        "views/purchase_order_line_views.xml",
        "views/res_company_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/sale_order_line_views.xml",
        "views/stock_location_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_move_views.xml",
        "views/stock_move_line_views.xml",
        "views/stock_picking_type_views.xml",
        # "views/stock_picking_views.xml",
        "views/stock_quant_views.xml",
        "views/menuitem_views.xml",
        "wizards/authorize_debt.xml",
        "wizards/invoice_cash_discount.xml",
        "wizards/invoice_line_price_history.xml",
        "wizards/pos_cash_transfer_wizard.xml",
        "wizards/purchase_order_line_price_history.xml",
        "wizards/sale_order_line_price_history.xml",
        "wizards/stock_quant_lot.xml",
    ],
    "demo": [
        "demo/ir_default_data.xml",
    ],
    "post_init_hook": "_post_init_marin",
    "assets": {
        "web.assets_backend": [
            "marin/static/src/widgets/**/*",
        ],
        # "point_of_sale._assets_pos": [
        #     "marin/static/src/pos/app/**/*",
        # ],
    },
    "installable": True,
    "application": True,
}
