{
    "name": "Marin",
    "summary": """
    Instance creator for Marin. This is the app.
    """,
    "author": "Agro Marin",
    "website": "https://www.agromarin.mx",
    "license": "OPL-1",
    "category": "Installer",
    "version": "saas~18.2.0.0.4",
    "depends": [
        "sale",
        "sale_management",
        "date_range",
        "board",
        "web_studio",
        # "work_team",
        "data_recycle",
        "knowledge",
        "appointment",
        "documents_expiry",
        "documents_product_asset",
        "hr_skills_survey",
        "hr_recruitment_survey",
        "documents_hr_recruitment",
        "hr_appraisal_survey",
        "hr_attendance",
        "base_approval",
        "project_forecast",
        "room",
        # "stock_fleet",
        "mrp_product_expiry",
        "stock_lot_rule",
        # "stock_3dpicking",
        "mrp_plm",
        "product_margin",
        "account_move_name_sequence",
        # "account_move_operation",
        "account_invoice_extract",
        "account_reports_cash_basis",
        "account_asset",
        "account_product_asset",
        "l10n_mx_edi_extended",
        "l10n_mx_avoid_reversal_entry",
        "l10n_mx_partner_blocklist",
        "documents_account",
        "documents_l10n_mx_edi",
        "hr_payroll_expense",
        "hr_expense_extract",
        "hr_contract_salary",
        "documents_hr_payroll",
        "l10n_mx_edi_payslip",
        "account_3way_match",
        "account_budget",
        # "purchase_requisition_stock",
        "mrp_landed_costs",
        "delivery",
        "stock_dropshipping",
        "sale_purchase_inter_company_rules",
        "account_invoice_margin_sale",
        # "stock_move_location",
        "sale_loyalty_delivery",
        # "sale_commission_margin",
        "pos_sale_margin",
        "pos_hr",
        # "website_sale_stock_renting",
        "website_event_sale",
        "website_slides",
        # "website_tiledesk",
        # "users_working_hours",
        "syngenta_edi",
        "gps_tracking",
        "stock_lot_rule",
        "product_abc_classification_sale_stock",
    ],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "data/ir_config_parameter_data.xml",
        "data/ir_actions_server_data.xml",
        "data/ir_cron_data.xml",
        "data/res_lang_data.xml",
        "data/ir_default_data.xml",
        "data/decimal_precision_data.xml",
        "data/mail_activity_data.xml",
        "data/res_config_settings_data.xml",
        "data/res_bank_data.xml",
        "data/product_removal_data.xml",
        "data/res.partner.category.csv",
        "data/uom_uom_data.xml",
        "data/ir_sequence_data.xml",
        "data/approval_category_data.xml",
        "data/res_partner_hectares_range_data.xml",
        "data/discuss_channel_data.xml",
        "data/documents_tag_data.xml",
        # "report/report_deliveryslip.xml",
        # "report/report_stock_picking_operations.xml",
        # "report/report_invoice.xml",
        # "report/report_payment.xml",
        "views/account_account_views.xml",
        "views/account_analytic_distribution_model_views.xml",
        "views/account_analytic_line_views.xml",
        "views/account_asset_views.xml",
        "views/account_bank_statement_views.xml",
        "views/account_journal_views.xml",
        "views/account_move_views.xml",
        "views/account_move_line_views.xml",
        "views/account_payment_views.xml",
        "views/documents_document_views.xml",
        "views/gps_tracking_device_views.xml",
        "views/hr_expense_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_payslip_run_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/pos_session_views.xml",
        "views/product_category_views.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/product_supplierinfo_views.xml",
        "views/project_task_views.xml",
        "views/project_project_views.xml",
        "views/purchase_order_views.xml",
        "views/purchase_order_line_views.xml",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
        "views/res_partner_profile_views.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/sale_order_line_views.xml",
        "views/sale_order_template_views.xml",
        "views/sale_target_views.xml",
        "views/stock_location_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_move_views.xml",
        "views/stock_move_line_views.xml",
        "views/stock_picking_type_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_picking_tracker_views.xml",
        "views/stock_quant_views.xml",
        "views/mrp_bom_views.xml",
        "views/approval_category_views.xml",
        "views/approval_request_views.xml",
        "report/invoice_line_in_views.xml",
        "report/invoice_line_out_views.xml",
        "report/invoice_line_out_team_views.xml",
        "report/invoice_line_out_team_yearly_views.xml",
        "report/pos_line_product_report_views.xml",
        "report/stock_need_report_views.xml",
        "report/purchase_bill_line_match_views.xml",
        "report/sales_master_report_views.xml",
        "wizards/authorize_debt.xml",
        "wizards/invoice_cash_discount.xml",
        "wizards/invoice_line_price_history.xml",
        "wizards/pos_cash_transfer_wizard.xml",
        "wizards/product_asset_log_import_views.xml",
        "wizards/purchase_order_line_price_history.xml",
        "wizards/sale_order_line_price_history.xml",
        "wizards/stock_quant_lot_update.xml",
        "wizards/product_asset_log_import_views.xml",
        "wizards/sale_target_wizard.xml",
        "wizards/res_config_settings_views.xml",
        "views/menuitem_views.xml",
    ],
    "pre_init_hook": "_pre_init_marin",
    "assets": {
        "web.assets_backend": [
            "marin/static/src/widgets/**/*",
        ],
    },
    "installable": True,
    "application": True,
}
