{
    "name": "Product asset",
    "summary": "Manage assets",
    "version": "1.0",
    "category": "Uncategorized",
    "author": "Odoo Community Association (OCA)",
    "depends": ["product_manufacturer", "hr"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/uom_uom_data.xml",
        "data/res_partner_data.xml",
        "data/product_category_data.xml",
        "data/product_attribute_data.xml",
        "views/product_template_views.xml",
        "views/stock_lot_views.xml",
        "views/product_asset_log_views.xml",
        #"views/product_asset_menuitem.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
}
