from . import product_template
from . import product_product
from . import res_company
from . import res_partner
from . import syngenta_sale_agreement
from . import syngenta_sale_document
from . import syngenta_sale_line
from . import syngenta_stock_document
from . import syngenta_stock_quant
