{
    "name": "GPS Tracking",
    "version": "1.5",
    "category": "Fleet Management",
    "summary": "Module to track GPS coordinates and display them on a map",
    "website": "https://agromarin.mx",
    "author": "Agro Marin",
    "depends": ["base_geoengine", "base_approval", "product_asset"],
    "data": [
        "security/res_group_security.xml",
        "security/ir_rule_security.xml",
        "security/ir.model.access.csv",
        "data/gps_tracking_config_data.xml",
        "data/ir_config_parameter_data.xml",
        "data/ir_actions_server.xml",
        "data/gps_geofence_type_data.xml",
        "report/gps_tracking_report_views.xml",
        "report/asset_loan_report_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_employee_public_views.xml",
        "views/gps_geofence_views.xml",
        "views/gps_geofence_type_views.xml",
        "views/gps_tracking_config_views.xml",
        "views/gps_tracking_device_views.xml",
        "views/geoengine_vector_layer_views.xml",
        "views/geoengine_raster_layer_views.xml",
        "views/gps_tracking_point_views.xml",
        "views/gps_tracking_templates.xml",
        "wizard/res_config_settings_views.xml",
        "views/gps_tracking_menus.xml",
    ],
    "assets": {
        "web.assets_backend": ["gps_tracking/static/src/**/*"],
    },
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
